question_data = [
    {"text": "English new wave musician Gary Numan founded the video game development company "
             "Facepunch Studios in March 2009.",
     "answer": "False"},
    {"text": "Leonardo DiCaprio won an Oscar for Best Actor in 2004 'The Aviator'.",
     "answer": "False"},
    {"text": "The 2010 film 'The Social Network' is a biographical drama film about MySpace founder Tom Anderson.",
     "answer": "False"},
    {"text": "The logo for Snapchat is a Bell.", "answer": "False"},
    {"text": "The United States was a member of the League of Nations.", "answer": "False"},
    {"text": "The full English name of the car manufacturer BMW is Bavarian Motor Works", "answer": "True"},
    {"text": "The main playable character of the 2015 RPG 'Undertale' is a monster.", "answer": "False"},
    {"text": "In Pokemon, Ash's Pikachu refuses to go into a pokeball.", "answer": "True"},
    {"text": "The name of the attack 'Kamehameha' in Dragon Ball Z was named after a famous king of Hawaii.",
     "answer": "True"},
    {"text": "In Pokemon Sun and Moon, a male Salandit can evolve to a Salazzle.", "answer": "False",},
    {"text": "In 'Undertale', the main character of the game is Sans.", "answer": "False"},
    {"text": "In Battlestar Galactica (2004), Cylons were created by man as cybernetic workers and soldiers.",
     "answer": "True"},
    {"text": "Adolf Hitler was tried at the Nuremberg trials.", "answer": "False"},
    {"text": "Kublai Khan is the grandchild of Genghis Khan?", "answer": "True"},
    {"text": "In 'Star Trek', Klingons are aliens.", "answer": "True"},
    {"text": "Hungary is the only country in the world beginning with H.", "answer": "False"},
    {"text": "The game 'Jetpack Joyride' was created by 'Redbrick Studios'.", "answer": "False"},
    {"text": "Lead Singer Rivers Cuomo of American rock band Weezer attended Harvard.", "answer": "True"},
    {"text": "'Resident Evil 7' is the first first-person Resident Evil game.", "answer": "False"},
    {"text": "The shotgun appears in every numbered Resident Evil game.", "answer": "True"}]
